# Generated by Django 5.2.9 on 2026-01-20 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_storageroom_current_temperature_and_more'),
        ('temperature', '0003_storageroom_alter_temperaturelog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturelog',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature_logs', to='inventory.storageroom'),
        ),
        migrations.AlterField(
            model_name='temperaturealert',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature_alerts', to='inventory.storageroom'),
        ),
        migrations.DeleteModel(
            name='StorageRoom',
        ),
    ]
