# Generated by Django 5.2.7 on 2026-02-08 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_remove_coldstorage_inv_cs_active_idx_and_more'),
        ('temperature', '0005_alter_temperaturelog_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='temperaturealert',
            index=models.Index(fields=['room', 'status'], name='temperature_room_id_972b83_idx'),
        ),
        migrations.AddIndex(
            model_name='temperaturealert',
            index=models.Index(fields=['status'], name='temperature_status_56bbb2_idx'),
        ),
        migrations.AddIndex(
            model_name='temperaturelog',
            index=models.Index(fields=['room', '-logged_at'], name='temperature_room_id_69b9e8_idx'),
        ),
    ]
