# Generated by Django 5.2.9 on 2025-12-16 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('paid', 'Paid'), ('failed', 'Failed')], default='requested', max_length=20)),
                ('method', models.CharField(blank=True, max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outward_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_request', to='inventory.outwardentry')),
            ],
        ),
    ]
