# Generated by Django 5.2.9 on 2025-12-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('operator', 'Operator')], max_length=20, null=True),
        ),
    ]
