# Generated by Django 5.2.7 on 2026-01-04 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0003_storageroom_alter_temperaturelog_options_and_more'),
        ('users', '0004_add_technician_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_storages',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='temperature.storageroom'),
        ),
        migrations.AddField(
            model_name='user',
            name='managed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
