# Generated by Django 5.2.7 on 2026-01-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_coldstorage_inwardentry_cold_storage'),
        ('users', '0005_user_assigned_storages_user_managed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='assigned_storages',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='inventory.coldstorage'),
        ),
    ]
