# Generated by Django 5.2.7 on 2026-01-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventory', '0012_alter_outwardentry_created_by'),
        ('users', '0006_alter_user_assigned_storages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('phone_number', 'managed_by')},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number', 'role'], name='users_user_phone_n_f020b3_idx'),
        ),
    ]
