# Generated by Django 5.2.7 on 2026-01-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_outwardentry_created_by'),
        ('users', '0007_allow_duplicate_phone_per_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_rooms',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='inventory.storageroom'),
        ),
    ]
