# Generated by Django 5.2.7 on 2026-02-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_assigned_rooms'),
    ]

    operations = [
        # Add index on managed_by field for faster filtering of staff members
        # This improves query performance when owners/managers list their staff
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['managed_by'], name='users_user_managed_idx'),
        ),
    ]
