# Generated by Django 5.2.7 on 2026-02-08 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_managed_idx',
        ),
    ]
