# Generated by Django 5.2.9 on 2025-12-16 05:26

import apps.inventory.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InwardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('crop_variety', models.CharField(blank=True, max_length=100)),
                ('size_grade', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('packaging_type', models.CharField(choices=[('bori', 'Bori'), ('crate', 'Crate'), ('box', 'Box')], max_length=20)),
                ('quality_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.inventory.models.inward_image_upload_to)),
                ('rack_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutwardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('packaging_type', models.CharField(choices=[('bori', 'Bori'), ('crate', 'Crate'), ('box', 'Box')], max_length=20)),
                ('receipt_number', models.CharField(editable=False, max_length=64, unique=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('other', 'Other')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(choices=[('farmer', 'Farmer'), ('vendor', 'Vendor')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
