# Generated by Django 5.2.9 on 2025-12-16 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inwardentry',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_inwards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outwardentry',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_outwards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outwardentry',
            name='inward_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outward_entries', to='inventory.inwardentry'),
        ),
        migrations.AddField(
            model_name='inwardentry',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inward_entries', to='inventory.person'),
        ),
    ]
