# Generated by Django 5.2.7 on 2025-12-30 06:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inwardentry',
            name='quality_rating',
        ),
        migrations.AddField(
            model_name='inwardentry',
            name='entry_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inwardentry',
            name='expected_storage_duration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inwardentry',
            name='quality_grade',
            field=models.CharField(choices=[('A', 'Grade A'), ('B', 'Grade B'), ('C', 'Grade C')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='inwardentry',
            name='storage_room',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
