# Generated by Django 5.2.7 on 2026-01-20 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inwardentry_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('capacity', models.DecimalField(blank=True, decimal_places=2, help_text='Capacity in MT', max_digits=12, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cold_storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='inventory.coldstorage')),
            ],
            options={
                'ordering': ['room_name'],
                'unique_together': {('cold_storage', 'room_name')},
            },
        ),
    ]
