# Generated by Django 5.2.9 on 2026-01-20 16:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_storageroom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='coldstorage',
            name='code',
            field=models.CharField(help_text='Code for the cold storage (unique per owner)', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='coldstorage',
            unique_together={('owner', 'code')},
        ),
    ]
