# Generated by Django 5.2.9 on 2026-01-20 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_person_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='cold_storage',
            field=models.ForeignKey(blank=True, help_text='Cold storage where this person does business', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='inventory.coldstorage'),
        ),
    ]
