# Generated by Django 5.2.9 on 2026-01-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_person_cold_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageroom',
            name='current_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Last recorded temperature in °C', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='storageroom',
            name='last_temp_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storageroom',
            name='max_temperature',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum acceptable temperature in °C', max_digits=5),
        ),
        migrations.AddField(
            model_name='storageroom',
            name='min_temperature',
            field=models.DecimalField(decimal_places=2, default=-5.0, help_text='Minimum acceptable temperature in °C', max_digits=5),
        ),
    ]
