# Generated by Django 5.2.9 on 2026-01-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_storageroom_current_temperature_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coldstorage',
            options={'ordering': ['name'], 'verbose_name': 'Storage', 'verbose_name_plural': 'Storages'},
        ),
        migrations.AddField(
            model_name='coldstorage',
            name='storage_type',
            field=models.CharField(choices=[('silo', 'Silos'), ('warehouse', 'Warehouse'), ('cold_storage', 'Cold Storage'), ('frozen_storage', 'Frozen Storage'), ('ripening_chamber', 'Ripening Chamber'), ('controlled_atmosphere', 'Controlled Atmosphere Storage')], default='cold_storage', max_length=50),
        ),
        migrations.AlterField(
            model_name='coldstorage',
            name='code',
            field=models.CharField(help_text='Code for the storage (unique per owner)', max_length=50),
        ),
    ]
