# Generated by Django 5.2.7 on 2026-02-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_outwardentry_created_by'),
    ]

    operations = [
        # Add index on is_active field for ColdStorage
        # Improves filtering performance when fetching active storages
        migrations.AddIndex(
            model_name='coldstorage',
            index=models.Index(fields=['is_active'], name='inv_cs_active_idx'),
        ),

        # Add index on entry_date field for InwardEntry
        # Speeds up time-based queries and date filtering
        migrations.AddIndex(
            model_name='inwardentry',
            index=models.Index(fields=['entry_date'], name='inv_inward_date_idx'),
        ),

        # Add composite index on (cold_storage, created_at) for InwardEntry
        # Optimizes dashboard queries that filter by storage and time range
        migrations.AddIndex(
            model_name='inwardentry',
            index=models.Index(fields=['cold_storage', 'created_at'], name='inv_inward_cs_created_idx'),
        ),

        # Add index on created_at field for OutwardEntry
        # Speeds up monthly aggregation queries in dashboard
        migrations.AddIndex(
            model_name='outwardentry',
            index=models.Index(fields=['created_at'], name='inv_outward_created_idx'),
        ),
    ]
