# Generated by Django 5.2.7 on 2026-02-08 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='coldstorage',
            name='inv_cs_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='inwardentry',
            name='inv_inward_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='outwardentry',
            name='inv_outward_created_idx',
        ),
        migrations.RenameIndex(
            model_name='inwardentry',
            new_name='inventory_i_cold_st_5203d4_idx',
            old_name='inv_inward_cs_created_idx',
        ),
        migrations.AddIndex(
            model_name='coldstorage',
            index=models.Index(fields=['owner', 'is_active'], name='inventory_c_owner_i_4b4e36_idx'),
        ),
        migrations.AddIndex(
            model_name='coldstorage',
            index=models.Index(fields=['manager', 'is_active'], name='inventory_c_manager_fc3bf9_idx'),
        ),
        migrations.AddIndex(
            model_name='inwardentry',
            index=models.Index(fields=['person', 'crop_name'], name='inventory_i_person__33be68_idx'),
        ),
        migrations.AddIndex(
            model_name='inwardentry',
            index=models.Index(fields=['created_by'], name='inventory_i_created_2abf27_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['created_by'], name='inventory_p_created_e54d07_idx'),
        ),
    ]
